import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for the robotics book
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Robotics Fundamentals',
      items: [
        'robotics/index',
        'robotics/ros2-basics',
        'robotics/nodes-topics-services',
        'robotics/rclpy-intro',
        'robotics/urdf-fundamentals',
      ],
    },
    {
      type: 'category',
      label: 'AI for Robotics',
      items: [
        'ai/index',
        'ai/machine-learning-robotics',
        'ai/computer-vision-robotics',
      ],
    },
    {
      type: 'category',
      label: 'Digital Twin & Simulation',
      items: [
        'simulation/index',
        'simulation/gazebo-intro',
      ],
    },
    {
      type: 'category',
      label: 'Humanoid Robotics',
      items: [
        'humanoid/index',
        'humanoid/control-systems',
        'humanoid/locomotion',
        'humanoid/manipulation',
      ],
    },
    {
      type: 'category',
      label: 'Safety & Best Practices',
      items: [
        'safety/robotics-safety',
      ],
    },
  ],
};

export default sidebars;
